### ISSUE TITLE
Allow For 24-Hour Reservations

### ISSUE THREAD

**Issue by erohrs2** [cseseniordesign/GarageStudioManager#142]
Allow some resources to be reserved at any time outside of operating hours. 

- [x] - Add a is_24_hour tinyint(1) to the resources table. 
- [ ] - Add a check in tools.rb for the 24 hours. 
- [x] - Add a checkbox to make a tool 24 hours in the create tool page.
- [x] - Make every existing resource be true for is_24_hour.

**Comment by jacoblharvey** [comment]
Definitely still a blocker for #215. The code in that branch will not function correctly without the changes made in this one.

**Comment by jburgher2** [comment]
> Definitely still a blocker for [#215](https://github.com/cseseniordesign/GarageStudioManager/issues/215). The code in that branch will not function correctly without the changes made in this one.

Yea, I went to move it to review/q&a on zenhub but for some reason it wouldn't move, so I thought the blocker was the thing stopping it. Likely it was just not immediately updating though.
