### ISSUE TITLE
New Member Popup

### ISSUE THREAD

**Issue by erohrs2** [cseseniordesign/GarageStudioManager#143]
- [x] Update popup for orientation sign ups
- [x] Update template for new_member_email
- [x] Update template for attended_orientation_email
~- [x] Hide member section from Edit User form~

**Comment by jharvey25** [comment]
Removed the task related to hiding the membership section of the Edit User form. This item will be discussed in our status meeting October 18 and will likely lead to a separate issue.

**Comment by jharvey25** [comment]
Task for hiding membership section will be handled in #212
