### ISSUE TITLE
Balance Refresh

### ISSUE THREAD

**Issue by erohrs2** [cseseniordesign/GarageStudioManager#165]
User Balance Refreshes per week

**Comment by btran27** [comment]
- [ ] new variable for balance
- [ ] find a place to for a user to view their current balance 
- [ ] track time/set up a weekly reset function for balance
- [ ] get initial balance from Max (is there balance difference between accounts at all?)

**Comment by btran27** [comment]
Fastener Count Feature and all related features are being pushed to a off-the-shelf product instead of Senior Design Team
